//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Udem.LlamaClothingCo.Presentation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillingAddress
    {
        public BillingAddress()
        {
            this.Client = new HashSet<Client>();
        }
    
        public string Street { get; set; }
        public string Number { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public Nullable<bool> IsAddressActive { get; set; }
        public int BillingAddressID { get; set; }
    
        public virtual ICollection<Client> Client { get; set; }
    }
}
