//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Udem.LlamaClothingCo.Presentation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public Client()
        {
            this.Sale = new HashSet<Sale>();
        }
    
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string RFC { get; set; }
        public Nullable<bool> IsClientActive { get; set; }
        public string Telephone { get; set; }
        public int ClientID { get; set; }
        public int BillingAddressID { get; set; }
        public int ClientTypeID { get; set; }
    
        public virtual ClientType ClientType { get; set; }
        public virtual ICollection<Sale> Sale { get; set; }
        public virtual BillingAddress BillingAddress { get; set; }
    }
}
