//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Udem.LlamaClothingCo.Presentation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public Sale()
        {
            this.SaleDetail = new HashSet<SaleDetail>();
        }
    
        public Nullable<double> SaleTotal { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public int SaleID { get; set; }
        public int ClientID { get; set; }
        public int ShippingAddressID { get; set; }
    
        public virtual ICollection<SaleDetail> SaleDetail { get; set; }
        public virtual Client Client { get; set; }
        public virtual ShippingAddress ShippingAddress { get; set; }
    }
}
